# Generated by Django 3.0.6 on 2020-05-14 06:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday'), ('SUN', 'Sunday')], default='MON', max_length=3)),
                ('datetime', models.DateTimeField()),
                ('max_interviewees', models.IntegerField()),
                ('max_interviewers', models.IntegerField()),
            ],
            options={
                'ordering': ['datetime'],
            },
        ),
        migrations.CreateModel(
            name='PersonalInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree_one', models.CharField(blank=True, max_length=150)),
                ('degree_two', models.CharField(blank=True, max_length=150)),
                ('major_one', models.CharField(blank=True, max_length=150)),
                ('major_two', models.CharField(blank=True, max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Interviewer',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('digital_impact', models.BooleanField(default=False)),
                ('personal_info', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='interviews.PersonalInfo')),
            ],
            options={
                'ordering': ['user'],
            },
        ),
        migrations.CreateModel(
            name='Interviewee',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('digital_impact', models.BooleanField(default=False)),
                ('previous_score', models.IntegerField()),
                ('personal_info', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='interviews.PersonalInfo')),
            ],
            options={
                'ordering': ['user'],
            },
        ),
        migrations.CreateModel(
            name='InterviewData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.CharField(blank=True, max_length=50, null=True)),
                ('full', models.BooleanField(default=False)),
                ('digital_impact', models.BooleanField(default=False)),
                ('interview_slot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='interviews.InterviewSlot')),
                ('interviewee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='interviews.Interviewee')),
                ('interviewer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='interviews.Interviewer')),
                ('invigilator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invigilator', to='interviews.Interviewer')),
                ('standby', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='standby', to='interviews.Interviewer')),
            ],
            options={
                'ordering': ['interview_slot'],
            },
        ),
    ]
