# Generated by Django 3.0.6 on 2020-05-17 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewdata',
            name='stream',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
