# Generated by Django 3.0.6 on 2020-08-05 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0002_interviewdata_stream'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewslot',
            name='current_interviewees',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='interviewslot',
            name='current_interviewers',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
