# Generated by Django 3.0.6 on 2020-08-06 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0003_auto_20200805_0621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewdata',
            name='interviewee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='interviews.Interviewee'),
        ),
        migrations.AlterField(
            model_name='interviewdata',
            name='interviewer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='interviews.Interviewer'),
        ),
    ]
