# Generated by Django 3.0.6 on 2020-08-06 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0004_auto_20200806_1235'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interviewdata',
            options={'ordering': ['datetime']},
        ),
        migrations.RemoveField(
            model_name='interviewdata',
            name='full',
        ),
        migrations.RemoveField(
            model_name='interviewdata',
            name='interview_slot',
        ),
        migrations.RemoveField(
            model_name='interviewdata',
            name='invigilator',
        ),
        migrations.RemoveField(
            model_name='interviewdata',
            name='standby',
        ),
        migrations.RemoveField(
            model_name='interviewdata',
            name='stream',
        ),
        migrations.RemoveField(
            model_name='interviewee',
            name='personal_info',
        ),
        migrations.RemoveField(
            model_name='interviewer',
            name='personal_info',
        ),
        migrations.AddField(
            model_name='interviewdata',
            name='current_interviewees',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='interviewdata',
            name='current_interviewers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='interviewdata',
            name='datetime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='interviewdata',
            name='max_interviewees',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='interviewdata',
            name='max_interviewers',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='interviewee',
            name='degree_one',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='interviewee',
            name='degree_two',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='interviewee',
            name='major_one',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='interviewee',
            name='major_two',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='interviewer',
            name='degree_one',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='interviewer',
            name='degree_two',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='interviewer',
            name='major_one',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='interviewer',
            name='major_two',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.DeleteModel(
            name='InterviewSlot',
        ),
        migrations.DeleteModel(
            name='PersonalInfo',
        ),
    ]
