# Generated by Django 3.0.6 on 2020-08-06 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0008_auto_20200806_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewdata',
            name='interviewees',
            field=models.ManyToManyField(blank=True, to='interviews.Interviewee'),
        ),
        migrations.AlterField(
            model_name='interviewdata',
            name='interviewer',
            field=models.ManyToManyField(blank=True, to='interviews.Interviewer'),
        ),
    ]
