# Generated by Django 3.0.6 on 2020-08-24 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0012_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Options',
            new_name='Option',
        ),
    ]
