# Generated by Django 3.0.6 on 2020-08-24 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0014_auto_20200824_0752'),
    ]

    operations = [
        migrations.RenameField(
            model_name='option',
            old_name='closed',
            new_name='option',
        ),
        migrations.AddField(
            model_name='option',
            name='name',
            field=models.CharField(default='hi', max_length=150),
            preserve_default=False,
        ),
    ]
