# Generated by Django 3.0.6 on 2020-08-24 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0015_auto_20200824_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='description',
            field=models.TextField(default='hi'),
            preserve_default=False,
        ),
    ]
