# Generated by Django 3.0.6 on 2020-08-24 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0017_auto_20200824_1338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interviewer',
            name='max_interviews',
        ),
    ]
