# Generated by Django 3.1 on 2020-08-26 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0018_remove_interviewer_max_interviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewdata',
            name='max_interviewers',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='interviewdata',
            name='room',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
