# Generated by Django 3.1 on 2020-09-04 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0019_auto_20200826_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewdata',
            name='max_interviewees',
            field=models.IntegerField(default=4),
        ),
    ]
