# Generated by Django 3.1.4 on 2021-01-31 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0020_auto_20200904_1629'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interviewdata',
            name='current_interviewees',
        ),
        migrations.RemoveField(
            model_name='interviewdata',
            name='current_interviewers',
        ),
    ]
